require "setup.autocmds"
require "setup.colors"
require "setup.keymaps"
require "setup.lsp"
require "setup.options"
require "setup.treesitter"

require "setup.plugins.coq"
require "setup.plugins.emmet"
require "setup.plugins.lualine"
require "setup.plugins.nerdtree"
require "setup.plugins.packer"
require "setup.plugins.sneak"
require "setup.plugins.surround"
require "setup.plugins.telescope"
